name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master-ns
  pull_request:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # odoo/odoo
          - python_version: "3.10"
            codename: jammy
            chrome_milestone: 139
            odoo_version: "18.0"
            odoo_org_repo: "Nosolotec/odoo"
            odoo_enterprise_org_repo: "Nosolotec/enterprise"
            image_name: py3.10-odoo18.0
            odoo_config_setting: "--config-setting=editable_mode=compat"
          - python_version: "3.10"
            codename: jammy
            odoo_version: "17.0"
            odoo_org_repo: "Nosolotec/odoo"
            odoo_enterprise_org_repo: "Nosolotec/enterprise"
            image_name: py3.10-odoo17.0
            odoo_config_setting: "--config-setting=editable_mode=compat"
    services:
      postgres:
        image: postgres:14.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          # no-cache: true  # Forzar rebuild sin cache
          build-args: |
            codename=${{ matrix.codename }}
            python_version=${{ matrix.python_version }}
            odoo_version=${{ matrix.odoo_version }}
            odoo_org_repo=${{ matrix.odoo_org_repo }}
            odoo_enterprise_org_repo=${{ matrix.odoo_enterprise_org_repo }}
            setuptools_constraint=${{ matrix.setuptools_constraint }}
            odoo_config_setting=${{ matrix.odoo_config_setting }}
            GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          tags: |
            ghcr.io/nosolotec/oca-ci/${{ matrix.image_name }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          cache-from: type=registry,ref=ghcr.io/nosolotec/oca-ci/${{ matrix.image_name }}:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tests
        run: docker run -v ${PWD}/tests:/mnt/tests --network=host -e PGHOST=localhost ghcr.io/nosolotec/oca-ci/${{ matrix.image_name }}:latest /mnt/tests/runtests.sh -v
        # Don't bother with Odoo 8 and 9 for now...
        if: ${{ matrix.odoo_version != '8.0' && matrix.odoo_version != '9.0' }}
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            codename=${{ matrix.codename }}
            python_version=${{ matrix.python_version }}
            odoo_version=${{ matrix.odoo_version }}
            odoo_org_repo=${{ matrix.odoo_org_repo }}
            odoo_enterprise_org_repo=${{ matrix.odoo_enterprise_org_repo }}
            setuptools_constraint=${{ matrix.setuptools_constraint }}
            odoo_config_setting=${{ matrix.odoo_config_setting }}
            GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          tags: |
            ghcr.io/nosolotec/oca-ci/${{ matrix.image_name }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=inline
          push: true
        if: ${{ github.repository_owner == 'Nosolotec' && github.ref == 'refs/heads/master-ns' }}
